# An ansible playbook to start the appropriate containers to configure the device
#
# note: docker commands are used and not the ansible docker utilities to remove
# additional dependencies on the target system

# Host dependencies:
#  - install ansible,
#  - create and copy ssh key
#  - run playbook with appropriate parameters
#    i.e. use the gateway tag to configure the device as a gateway

# NOTE: Linux microPlatform personalities managed by the agent
# This job
#   1. copies the systemd job to launch the agent process on boot
#   2. creates a compose config file (used by the agent)
#   3. reboots

# This task removes all containers
- hosts: all
  gather_facts: no
  tasks:
  - name: Cleanup for containers for group roll-out
    command: sh -c "if [ $(docker ps -a -q | head -c1 | wc -c) -ne 0 ]; then "\
                       "docker rm -f $(docker ps -aq); "\
                   "fi"
  tags:
    - cleanall
    - demo

# configure agent
- hosts: all
  gather_facts: no
  tasks:
  - name: copy run script
    copy:
      src: osfagent.sh
      dest: /home/linaro/osfagent.sh
      mode: 0755
  - name: copy osfagent service
    copy:
      src: osfagent.service
      dest: /etc/systemd/system/osfagent.service
  - name: copy osftargest.conf
    copy:
      src: targets/{{ target }}
      dest: /home/linaro/osftargets.conf
  tags:
    - microPlatform
    - demo

# gateway
- hosts: all
  gather_facts: no
  tasks:
  - name: gateway
    command: sh -c "echo https://github.com/akbennett/docker-compose-gateway master "\
                   ">> /home/linaro/osftargets.conf"
  tags:
    - gateway
    - demo

# freeboard
- hosts: all
  gather_facts: no
  tasks:
  - name: freeboard
    command: sh -c "echo https://github.com/akbennett/docker-compose-freeboard master "\
                   ">> /home/linaro/osftargets.conf"
  tags:
    - freeboard
    - demo

# enable service
- hosts: all
  gather_facts: no
  tasks:
  - name: enable service
    become: true
    become_method: sudo
    systemd:
      name: osfagent
      enabled: yes
      state: reloaded
  tags:
    - service
    - demo
